# Generated by Django 3.0.4 on 2020-03-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydata',
            name='parking_period_from',
            field=models.DateTimeField(null=True, verbose_name='Postój od'),
        ),
        migrations.AlterField(
            model_name='entrydata',
            name='parking_period_to',
            field=models.DateTimeField(null=True, verbose_name='Postój do'),
        ),
    ]
