# Generated by Django 3.0.4 on 2020-03-27 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0003_auto_20200328_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrydata',
            name='parking_place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='marine.ParkingPlace', verbose_name='Miejsce postoju'),
        ),
    ]
