# Generated by Django 3.0.4 on 2020-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0005_auto_20200402_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplace',
            name='occupied_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Occupied to'),
        ),
    ]
